var images = [
    "/images/background1.jpg",
    "/images/background2.jpg",
    "/images/background3.jpg",
    "/images/background4.jpg",
    "/images/background5.jpg",
    "/images/gallery/meeting/m01.jpg",
    "/images/gallery/meeting/m02.jpg",
    "/images/gallery/meeting/m03.jpg",
    "/images/gallery/meeting/m04.jpg",
    "/images/gallery/meeting/m05.jpg",
    "/images/gallery/meeting/m06.jpg",
    "/images/gallery/friendship/f01.jpg",
    "/images/gallery/friendship/f02.jpg",
    "/images/gallery/friendship/f03.jpg",
    "/images/gallery/friendship/f04.jpg",
    "/images/gallery/friendship/f05.jpg",
    "/images/gallery/friendship/f06.jpg",
    "/images/gallery/friendship/f07.jpg",
    "/images/gallery/friendship/f08.jpg",
    "/images/gallery/friendship/f09.jpg",
    "/images/gallery/proposal/p01.jpg",
    "/images/gallery/proposal/p02.jpg",
    "/images/gallery/proposal/p03.jpg",
    "/images/gallery/proposal/p04.jpg",
    "/images/gallery/proposal/p05.jpg",
    "/images/gallery/proposal/p06.jpg",
    "/images/gallery/proposal/p07.jpg",
    "/images/gallery/proposal/p08.jpg",
    "/images/gallery/proposal/p09.jpg",
    "/images/gallery/proposal/p10.jpg",
    "/images/gallery/engagement/e01.jpg",
    "/images/gallery/engagement/e02.jpg",
    "/images/gallery/engagement/e03.jpg",
    "/images/gallery/engagement/e04.jpg",
    "/images/gallery/engagement/e05.jpg",
    "/images/gallery/engagement/e06.jpg",
    "/images/gallery/engagement/e07.jpg",
    "/images/gallery/engagement/e08.jpg",
    "/images/gallery/engagement/e09.jpg",
    "/images/gallery/engagement/e10.jpg",
    "/images/gallery/engagement/e11.jpg",
    "/images/gallery/engagement/e12.jpg",
];

for (var i = 0; i < images.length; i += 1) {
    var image = new Image();
    image.src = images[i];   
}
